/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package teatrohanabi;
import Source.*;
import Clases.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar
 */
public class InterfazLogin extends javax.swing.JFrame {

    /** Creates new form InterfazLogin */
    public InterfazLogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logo_login = new JPanelBackground("logo.png");
        JPContenedor = new RoundedPanel(15, new java.awt.Color(70,70,70));
        jButton1 = new javax.swing.JButton();
        password_logo = new JPanelBackground("lock.png");
        jLabel3 = new javax.swing.JLabel();
        JPPassword = new javax.swing.JTextField();
        JPUsuario = new javax.swing.JTextField();
        user_logo = new JPanelBackground("user.png");
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 61, 61));
        jPanel1.setForeground(new java.awt.Color(245, 218, 218));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Bienvenido a Teatro Hanabi!");

        logo_login.setOpaque(false);

        org.jdesktop.layout.GroupLayout logo_loginLayout = new org.jdesktop.layout.GroupLayout(logo_login);
        logo_login.setLayout(logo_loginLayout);
        logo_loginLayout.setHorizontalGroup(
            logo_loginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 76, Short.MAX_VALUE)
        );
        logo_loginLayout.setVerticalGroup(
            logo_loginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 63, Short.MAX_VALUE)
        );

        JPContenedor.setBackground(new java.awt.Color(60, 60, 60));
        JPContenedor.setForeground(new java.awt.Color(60, 60, 60));
        JPContenedor.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(247, 246, 242));
        jButton1.setText("Iniciar Sesión");
        jButton1.setPreferredSize(new java.awt.Dimension(107, 32));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        password_logo.setOpaque(false);

        org.jdesktop.layout.GroupLayout password_logoLayout = new org.jdesktop.layout.GroupLayout(password_logo);
        password_logo.setLayout(password_logoLayout);
        password_logoLayout.setHorizontalGroup(
            password_logoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 24, Short.MAX_VALUE)
        );
        password_logoLayout.setVerticalGroup(
            password_logoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 25, Short.MAX_VALUE)
        );

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");

        JPPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPPasswordActionPerformed(evt);
            }
        });

        JPUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPUsuarioActionPerformed(evt);
            }
        });

        user_logo.setOpaque(false);
        user_logo.setPreferredSize(new java.awt.Dimension(24, 24));

        org.jdesktop.layout.GroupLayout user_logoLayout = new org.jdesktop.layout.GroupLayout(user_logo);
        user_logo.setLayout(user_logoLayout);
        user_logoLayout.setHorizontalGroup(
            user_logoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 24, Short.MAX_VALUE)
        );
        user_logoLayout.setVerticalGroup(
            user_logoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 24, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");

        org.jdesktop.layout.GroupLayout JPContenedorLayout = new org.jdesktop.layout.GroupLayout(JPContenedor);
        JPContenedor.setLayout(JPContenedorLayout);
        JPContenedorLayout.setHorizontalGroup(
            JPContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPContenedorLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(JPContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(JPContenedorLayout.createSequentialGroup()
                        .add(password_logo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(JPContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel3)
                            .add(JPPassword)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .add(JPContenedorLayout.createSequentialGroup()
                        .add(user_logo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(JPContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(JPUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        JPContenedorLayout.setVerticalGroup(
            JPContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPContenedorLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(JPContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(JPUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(user_logo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(43, 43, 43)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(JPContenedorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(JPPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(password_logo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(34, 34, 34)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(31, 31, 31))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(logo_login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(160, 160, 160))))
            .add(jPanel1Layout.createSequentialGroup()
                .add(88, 88, 88)
                .add(JPContenedor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(jLabel2)
                .add(24, 24, 24)
                .add(logo_login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(JPContenedor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JPPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPPasswordActionPerformed

    private void JPUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPUsuarioActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        if(!(JPUsuario.getText().equals("") || JPPassword.getText().equals(""))){
            Usuarios usu = new Usuarios(
                JPUsuario.getText(),
                JPPassword.getText());
            try{
                if(usu.Login()){
                    if(usu.get_estatus()){
                        Interfaz gui = new Interfaz(usu);
                        gui.setVisible(true);
                        this.setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(null, "Usuario desactivado, ADIOS !!!");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario o password incorrecto");
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPContenedor;
    private javax.swing.JTextField JPPassword;
    private javax.swing.JTextField JPUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logo_login;
    private javax.swing.JPanel password_logo;
    private javax.swing.JPanel user_logo;
    // End of variables declaration//GEN-END:variables

}
