/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package teatrohanabi;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import Source.*;
import Clases.*;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

/**
 *
 * @author Cesar
 */
public class Interfaz extends javax.swing.JFrame {
    Global global = new Global();
    String usuarioSession = "";
    /** Creates new form Interfaz */
    public Interfaz() {
        initComponents();
        this.setMenuOptions("Obras");
    }
    
    /** Creates new form Interfaz */
    public Interfaz(Usuarios usu) {
        initComponents();
        usuarioSession = usu.get_usuario();
        if(usu.get_puesto().equals("Empleado")){
            Obras.setVisible(false);
            Reportes.setVisible(false);
            Usuarios.setVisible(false);
            this.setMenuOptions("Boletos");
        }else{
            this.setMenuOptions("Obras");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new RoundedPanel(15, new java.awt.Color(250,51,51));
        Logo = new JPanelBackground("logo.png");
        jLabel1 = new javax.swing.JLabel();
        Boletos = new RoundedButton();
        Reportes = new RoundedButton();
        Usuarios = new RoundedButton();
        Obras = new RoundedButton();
        CerrarSesion = new RoundedButton();
        content = new javax.swing.JPanel();
        contentOptions = new javax.swing.JPanel();
        JPReportes = new RoundedPanel(15, new java.awt.Color(70,70,70));
        jButton2 = new RoundedButton();
        jButton7 = new RoundedButton();
        jButton8 = new RoundedButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JPBoletos = new RoundedPanel(15, new java.awt.Color(70,70,70));
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        JCBoletosObra = new javax.swing.JComboBox<>();
        JCBoletosNAsientos = new javax.swing.JComboBox<>();
        JCBoletosVip = new javax.swing.JComboBox<>();
        JCBoletosNombreCli = new javax.swing.JTextField();
        JCBoletosTelCli = new javax.swing.JTextField();
        JCBoletosEdadCli = new javax.swing.JTextField();
        JBBoletosRegistro = new RoundedButton();
        JPUsuarios = new RoundedPanel(15, new java.awt.Color(70,70,70));
        JPUsuariosContent = new javax.swing.JPanel();
        UsuariosContentAgregar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JTUsuUsuario = new javax.swing.JTextField();
        JTUsuPassword = new javax.swing.JTextField();
        JTUsuNombre = new javax.swing.JTextField();
        JCUsuPuesto = new javax.swing.JComboBox<>();
        JBUsuariosRegistrar = new RoundedButton();
        UsuariosContentLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTListaUsuarios = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        JPUsuariosHeader = new javax.swing.JPanel();
        JBUsuariosOption = new RoundedButton();
        JLUsuariosTitulo = new javax.swing.JLabel();
        JPObras = new RoundedPanel(15, new java.awt.Color(70,70,70));
        jButton5 = new RoundedButton();
        txt_asientos = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        jButton1 = new RoundedButton();
        jButton3 = new RoundedButton();
        txt_nombre = new javax.swing.JTextField();
        jButton4 = new RoundedButton();
        txt_genero = new javax.swing.JTextField();
        txt_buscar = new javax.swing.JTextField();
        jButton6 = new RoundedButton();
        txt_Duracion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        JLTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(60, 60, 60));

        background.setBackground(new java.awt.Color(60, 60, 60));
        background.setPreferredSize(new java.awt.Dimension(800, 600));

        menu.setBackground(new java.awt.Color(250, 51, 51));
        menu.setMaximumSize(new java.awt.Dimension(150, 520));
        menu.setMinimumSize(new java.awt.Dimension(150, 520));
        menu.setOpaque(false);
        menu.setPreferredSize(new java.awt.Dimension(150, 520));

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setPreferredSize(new java.awt.Dimension(118, 96));
        Logo.setRequestFocusEnabled(false);

        org.jdesktop.layout.GroupLayout LogoLayout = new org.jdesktop.layout.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 118, Short.MAX_VALUE)
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 96, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Teatro Hanabi");

        Boletos.setLabel("Boletos");
        Boletos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Boletos.setText("Boletos");
        Boletos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boletos.setPreferredSize(new java.awt.Dimension(130, 50));
        Boletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoletosMousePressed(evt);
            }
        });

        Reportes.setLabel("Reportes");
        Reportes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Reportes.setText("Reportes");
        Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reportes.setPreferredSize(new java.awt.Dimension(130, 50));
        Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReportesMousePressed(evt);
            }
        });

        Usuarios.setLabel("Usuarios");
        Usuarios.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Usuarios.setText("Usuarios");
        Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Usuarios.setPreferredSize(new java.awt.Dimension(130, 50));
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuariosMousePressed(evt);
            }
        });

        Obras.setLabel("Obras");
        Obras.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Obras.setText("Obras");
        Obras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Obras.setPreferredSize(new java.awt.Dimension(130, 50));
        Obras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ObrasMousePressed(evt);
            }
        });

        CerrarSesion.setLabel("Cerrar sesión");
        CerrarSesion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesion.setPreferredSize(new java.awt.Dimension(130, 50));
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarSesionMousePressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout menuLayout = new org.jdesktop.layout.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(menuLayout.createSequentialGroup()
                .addContainerGap()
                .add(menuLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(CerrarSesion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Reportes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Boletos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Usuarios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Obras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(menuLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(Logo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(menuLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(Logo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(Boletos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(Obras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(Reportes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(Usuarios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(CerrarSesion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(50, 50, 50))
        );

        content.setBackground(new java.awt.Color(60, 60, 60));
        content.setPreferredSize(new java.awt.Dimension(600, 550));

        contentOptions.setBackground(new java.awt.Color(60, 60, 60));
        contentOptions.setPreferredSize(new java.awt.Dimension(580, 510));

        JPReportes.setBackground(new java.awt.Color(70, 70, 70));
        JPReportes.setOpaque(false);
        JPReportes.setPreferredSize(new java.awt.Dimension(550, 490));

        jButton2.setLabel("Venta de Boletos");
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton2.setText("Venta de Boletos");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setLabel("Obras");
        jButton7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton7.setText("Obras");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });

        jButton8.setLabel("Usuarios");
        jButton8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton8.setText("Usuarios");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(245, 245, 245));
        jLabel8.setText("Reporte de Obras");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(245, 245, 245));
        jLabel9.setText("Reporte de Usuarios");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(245, 245, 245));
        jLabel10.setText("Reporte de Boletos vendidos");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(245, 245, 245));
        jLabel11.setText("Click en el boton para exportar la base de datos en un pdf");

        org.jdesktop.layout.GroupLayout JPReportesLayout = new org.jdesktop.layout.GroupLayout(JPReportes);
        JPReportes.setLayout(JPReportesLayout);
        JPReportesLayout.setHorizontalGroup(
            JPReportesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPReportesLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 417, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, JPReportesLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(JPReportesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel10))
                .add(145, 145, 145))
        );
        JPReportesLayout.setVerticalGroup(
            JPReportesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPReportesLayout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jLabel11)
                .add(40, 40, 40)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(jLabel9)
                .add(17, 17, 17)
                .add(jButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel10)
                .add(17, 17, 17)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        JPBoletos.setBackground(new java.awt.Color(70, 70, 70));
        JPBoletos.setForeground(new java.awt.Color(0, 0, 0));
        JPBoletos.setOpaque(false);
        JPBoletos.setPreferredSize(new java.awt.Dimension(550, 490));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(245, 245, 245));
        jLabel16.setText("Num.Asiento");

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(245, 245, 245));
        jLabel17.setText("Obra");

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(245, 245, 245));
        jLabel18.setText("VIP");

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(245, 245, 245));
        jLabel19.setText("Datos del Cliente");

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(245, 245, 245));
        jLabel20.setText("Nombre");

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(245, 245, 245));
        jLabel21.setText("Telefono");

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(245, 245, 245));
        jLabel22.setText("Edad");

        JCBoletosObra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCBoletosObra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCBoletosObraItemStateChanged(evt);
            }
        });

        JCBoletosNAsientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion" }));
        JCBoletosNAsientos.setEnabled(false);

        JCBoletosVip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion", "Si", "No" }));

        JBBoletosRegistro.setLabel("Agregar");
        JBBoletosRegistro.setText("jButton3");
        JBBoletosRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JBBoletosRegistroMousePressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout JPBoletosLayout = new org.jdesktop.layout.GroupLayout(JPBoletos);
        JPBoletos.setLayout(JPBoletosLayout);
        JPBoletosLayout.setHorizontalGroup(
            JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPBoletosLayout.createSequentialGroup()
                .add(94, 94, 94)
                .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, JPBoletosLayout.createSequentialGroup()
                        .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(84, 84, 84))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, JPBoletosLayout.createSequentialGroup()
                        .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(JPBoletosLayout.createSequentialGroup()
                                .add(35, 35, 35)
                                .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel16, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, JPBoletosLayout.createSequentialGroup()
                                .add(40, 40, 40)
                                .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(18, 18, 18)
                        .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(JCBoletosEdadCli)
                            .add(JCBoletosTelCli)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, JCBoletosObra, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, JCBoletosNAsientos, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, JCBoletosVip, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, JCBoletosNombreCli, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(137, 137, 137))
            .add(JPBoletosLayout.createSequentialGroup()
                .add(202, 202, 202)
                .add(JBBoletosRegistro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBoletosLayout.setVerticalGroup(
            JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPBoletosLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(JCBoletosObra)
                    .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(JCBoletosNAsientos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(JCBoletosVip, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .add(36, 36, 36)
                .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(JCBoletosNombreCli, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(JCBoletosTelCli, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(JPBoletosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(JCBoletosEdadCli, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(JBBoletosRegistro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(31, 31, 31))
        );

        JPUsuarios.setBackground(new java.awt.Color(70, 70, 70));
        JPUsuarios.setOpaque(false);
        JPUsuarios.setPreferredSize(new java.awt.Dimension(550, 490));

        JPUsuariosContent.setOpaque(false);
        JPUsuariosContent.setPreferredSize(new java.awt.Dimension(550, 410));

        UsuariosContentAgregar.setOpaque(false);
        UsuariosContentAgregar.setPreferredSize(new java.awt.Dimension(550, 410));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(245, 245, 245));
        jLabel12.setText("Usuario");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(245, 245, 245));
        jLabel13.setText("Contraseña");

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(245, 245, 245));
        jLabel14.setText("Nombre");

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(245, 245, 245));
        jLabel15.setText("Puesto");

        JTUsuUsuario.setForeground(new java.awt.Color(245, 245, 245));
        JTUsuUsuario.setOpaque(false);

        JTUsuPassword.setForeground(new java.awt.Color(245, 245, 245));
        JTUsuPassword.setOpaque(false);

        JTUsuNombre.setForeground(new java.awt.Color(245, 245, 245));
        JTUsuNombre.setOpaque(false);

        JCUsuPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una Opcion", "Empleado", "Administrativo" }));

        JBUsuariosRegistrar.setLabel("Agregar");
        JBUsuariosRegistrar.setText("jButton3");
        JBUsuariosRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JBUsuariosRegistrarMousePressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout UsuariosContentAgregarLayout = new org.jdesktop.layout.GroupLayout(UsuariosContentAgregar);
        UsuariosContentAgregar.setLayout(UsuariosContentAgregarLayout);
        UsuariosContentAgregarLayout.setHorizontalGroup(
            UsuariosContentAgregarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(UsuariosContentAgregarLayout.createSequentialGroup()
                .add(111, 111, 111)
                .add(UsuariosContentAgregarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(UsuariosContentAgregarLayout.createSequentialGroup()
                        .add(jLabel12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(12, 12, 12)
                        .add(JTUsuUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, UsuariosContentAgregarLayout.createSequentialGroup()
                        .add(jLabel14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(12, 12, 12)
                        .add(JTUsuNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, UsuariosContentAgregarLayout.createSequentialGroup()
                        .add(jLabel13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .add(12, 12, 12)
                        .add(JTUsuPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, UsuariosContentAgregarLayout.createSequentialGroup()
                        .add(jLabel15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(JCUsuPuesto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(149, 149, 149))
            .add(UsuariosContentAgregarLayout.createSequentialGroup()
                .add(199, 199, 199)
                .add(JBUsuariosRegistrar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsuariosContentAgregarLayout.setVerticalGroup(
            UsuariosContentAgregarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(UsuariosContentAgregarLayout.createSequentialGroup()
                .add(47, 47, 47)
                .add(UsuariosContentAgregarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(JTUsuUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(UsuariosContentAgregarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(JTUsuPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(UsuariosContentAgregarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(JTUsuNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(UsuariosContentAgregarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(JCUsuPuesto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(41, 41, 41)
                .add(JBUsuariosRegistrar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        UsuariosContentLista.setOpaque(false);
        UsuariosContentLista.setPreferredSize(new java.awt.Dimension(550, 410));

        jScrollPane1.setForeground(new java.awt.Color(60, 63, 65));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 410));

        JTListaUsuarios.setForeground(new java.awt.Color(60, 63, 65));
        JTListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuario", "Nombre", "Puesto", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTListaUsuarios.setOpaque(false);
        JTListaUsuarios.setPreferredSize(new java.awt.Dimension(550, 410));
        JTListaUsuarios.setSelectionForeground(new java.awt.Color(60, 63, 65));
        jScrollPane1.setViewportView(JTListaUsuarios);

        jLabel23.setText("Usuario a deshabilitar");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout UsuariosContentListaLayout = new org.jdesktop.layout.GroupLayout(UsuariosContentLista);
        UsuariosContentLista.setLayout(UsuariosContentListaLayout);
        UsuariosContentListaLayout.setHorizontalGroup(
            UsuariosContentListaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(UsuariosContentListaLayout.createSequentialGroup()
                .addContainerGap()
                .add(UsuariosContentListaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .add(UsuariosContentListaLayout.createSequentialGroup()
                        .add(UsuariosContentListaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UsuariosContentListaLayout.setVerticalGroup(
            UsuariosContentListaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, UsuariosContentListaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel23)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 335, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout JPUsuariosContentLayout = new org.jdesktop.layout.GroupLayout(JPUsuariosContent);
        JPUsuariosContent.setLayout(JPUsuariosContentLayout);
        JPUsuariosContentLayout.setHorizontalGroup(
            JPUsuariosContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 550, Short.MAX_VALUE)
            .add(JPUsuariosContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(JPUsuariosContentLayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(UsuariosContentAgregar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
            .add(JPUsuariosContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(JPUsuariosContentLayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(UsuariosContentLista, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        JPUsuariosContentLayout.setVerticalGroup(
            JPUsuariosContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 410, Short.MAX_VALUE)
            .add(JPUsuariosContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(JPUsuariosContentLayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(UsuariosContentAgregar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
            .add(JPUsuariosContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(JPUsuariosContentLayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(UsuariosContentLista, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        JPUsuariosHeader.setOpaque(false);
        JPUsuariosHeader.setPreferredSize(new java.awt.Dimension(550, 70));

        JBUsuariosOption.setLabel("Agregar");
        JBUsuariosOption.setText("jButton2");
        JBUsuariosOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBUsuariosOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JBUsuariosOptionMousePressed(evt);
            }
        });

        JLUsuariosTitulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        JLUsuariosTitulo.setForeground(new java.awt.Color(245, 245, 245));
        JLUsuariosTitulo.setText("Listado de Obras");

        org.jdesktop.layout.GroupLayout JPUsuariosHeaderLayout = new org.jdesktop.layout.GroupLayout(JPUsuariosHeader);
        JPUsuariosHeader.setLayout(JPUsuariosHeaderLayout);
        JPUsuariosHeaderLayout.setHorizontalGroup(
            JPUsuariosHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, JPUsuariosHeaderLayout.createSequentialGroup()
                .add(17, 17, 17)
                .add(JLUsuariosTitulo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 273, Short.MAX_VALUE)
                .add(JBUsuariosOption, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPUsuariosHeaderLayout.setVerticalGroup(
            JPUsuariosHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPUsuariosHeaderLayout.createSequentialGroup()
                .add(15, 15, 15)
                .add(JPUsuariosHeaderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(JBUsuariosOption, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(JLUsuariosTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout JPUsuariosLayout = new org.jdesktop.layout.GroupLayout(JPUsuarios);
        JPUsuarios.setLayout(JPUsuariosLayout);
        JPUsuariosLayout.setHorizontalGroup(
            JPUsuariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPUsuariosLayout.createSequentialGroup()
                .add(JPUsuariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(JPUsuariosContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(JPUsuariosHeader, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, Short.MAX_VALUE))
        );
        JPUsuariosLayout.setVerticalGroup(
            JPUsuariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, JPUsuariosLayout.createSequentialGroup()
                .add(JPUsuariosHeader, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                .add(JPUsuariosContent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        JPObras.setBackground(new java.awt.Color(70, 70, 70));
        JPObras.setOpaque(false);
        JPObras.setPreferredSize(new java.awt.Dimension(550, 490));
        JPObras.setRequestFocusEnabled(false);

        jButton5.setLabel("Generar PDF");
        jButton5.setText("Generar PDF");
        jButton5.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt_asientos.setPreferredSize(new java.awt.Dimension(123, 35));

        jButton1.setLabel("Registrar");
        jButton1.setText("Registrar");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setLabel("Modificar");
        jButton3.setText("Modificar");
        jButton3.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txt_nombre.setPreferredSize(new java.awt.Dimension(123, 35));

        jButton4.setLabel("Eliminar");
        jButton4.setText("Eliminar");
        jButton4.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txt_genero.setPreferredSize(new java.awt.Dimension(123, 35));

        txt_buscar.setPreferredSize(new java.awt.Dimension(80, 35));

        jButton6.setLabel("Buscar");
        jButton6.setText("Buscar");
        jButton6.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txt_Duracion.setPreferredSize(new java.awt.Dimension(123, 35));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 245, 245));
        jLabel3.setText("Duracion");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 245, 245));
        jLabel2.setText("Genero");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 245, 245));
        jLabel5.setText("Fecha/Hora");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 245, 245));
        jLabel6.setText("Ingrese el ID de la obra:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 245, 245));
        jLabel4.setText("Nombre Obra");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 245, 245));
        jLabel7.setText("Num-Acientos");

        status.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        status.setForeground(new java.awt.Color(245, 245, 245));

        org.jdesktop.layout.GroupLayout JPObrasLayout = new org.jdesktop.layout.GroupLayout(JPObras);
        JPObras.setLayout(JPObrasLayout);
        JPObrasLayout.setHorizontalGroup(
            JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPObrasLayout.createSequentialGroup()
                .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(JPObrasLayout.createSequentialGroup()
                        .add(78, 78, 78)
                        .add(jButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(JPObrasLayout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(status))
                    .add(JPObrasLayout.createSequentialGroup()
                        .add(136, 136, 136)
                        .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txt_genero, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txt_Duracion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txt_nombre, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, JPObrasLayout.createSequentialGroup()
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(JPObrasLayout.createSequentialGroup()
                                    .add(40, 40, 40)
                                    .add(txt_asientos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, JPObrasLayout.createSequentialGroup()
                                .add(40, 40, 40)
                                .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(txt_fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(JPObrasLayout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(28, 28, 28)
                        .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(JPObrasLayout.createSequentialGroup()
                                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txt_buscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(JPObrasLayout.createSequentialGroup()
                                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(38, 38, 38)
                                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        JPObrasLayout.setVerticalGroup(
            JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPObrasLayout.createSequentialGroup()
                .add(47, 47, 47)
                .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(JPObrasLayout.createSequentialGroup()
                        .add(jLabel4)
                        .add(12, 12, 12)
                        .add(txt_nombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(JPObrasLayout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(txt_asientos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txt_fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txt_genero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txt_Duracion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(41, 41, 41)
                .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(JPObrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txt_buscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(36, 36, 36)
                .add(status)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout contentOptionsLayout = new org.jdesktop.layout.GroupLayout(contentOptions);
        contentOptions.setLayout(contentOptionsLayout);
        contentOptionsLayout.setHorizontalGroup(
            contentOptionsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentOptionsLayout.createSequentialGroup()
                .add(JPReportes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 30, Short.MAX_VALUE))
            .add(contentOptionsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(contentOptionsLayout.createSequentialGroup()
                    .add(JPBoletos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 30, Short.MAX_VALUE)))
            .add(contentOptionsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(contentOptionsLayout.createSequentialGroup()
                    .add(JPUsuarios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 30, Short.MAX_VALUE)))
            .add(contentOptionsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(contentOptionsLayout.createSequentialGroup()
                    .add(JPObras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 30, Short.MAX_VALUE)))
        );
        contentOptionsLayout.setVerticalGroup(
            contentOptionsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentOptionsLayout.createSequentialGroup()
                .add(JPReportes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 20, Short.MAX_VALUE))
            .add(contentOptionsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(contentOptionsLayout.createSequentialGroup()
                    .add(JPBoletos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 20, Short.MAX_VALUE)))
            .add(contentOptionsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(contentOptionsLayout.createSequentialGroup()
                    .add(JPUsuarios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 20, Short.MAX_VALUE)))
            .add(contentOptionsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(contentOptionsLayout.createSequentialGroup()
                    .add(JPObras, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        header.setBackground(new java.awt.Color(60, 60, 60));
        header.setPreferredSize(new java.awt.Dimension(580, 50));

        JLTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JLTitulo.setForeground(new java.awt.Color(245, 245, 245));
        JLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTitulo.setText("INICIO");

        org.jdesktop.layout.GroupLayout headerLayout = new org.jdesktop.layout.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .add(JLTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(213, 213, 213))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(headerLayout.createSequentialGroup()
                .addContainerGap()
                .add(JLTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout contentLayout = new org.jdesktop.layout.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentLayout.createSequentialGroup()
                .addContainerGap()
                .add(contentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(contentOptions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(header, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 550, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(contentLayout.createSequentialGroup()
                .add(header, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(contentOptions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout backgroundLayout = new org.jdesktop.layout.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backgroundLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .add(menu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(content, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, content, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(backgroundLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(menu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(background, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(background, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BoletosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoletosMousePressed
        this.setMenuOptions("Boletos");
    }//GEN-LAST:event_BoletosMousePressed

    private void ReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMousePressed
        this.setMenuOptions("Reportes");
    }//GEN-LAST:event_ReportesMousePressed

    private void UsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMousePressed
        this.setMenuOptions("Usuarios");
    }//GEN-LAST:event_UsuariosMousePressed

    private void CerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMousePressed
        InterfazLogin gui = new InterfazLogin();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CerrarSesionMousePressed

    private void ObrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObrasMousePressed
        this.setMenuOptions("Obras");
    }//GEN-LAST:event_ObrasMousePressed

    private void JBUsuariosOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBUsuariosOptionMousePressed
        String menu = JLUsuariosTitulo.getText();
        setMenuUsuariosOptions(menu.equals("Agregar usuario")? "Lista de usuarios": "Agregar usuario");
    }//GEN-LAST:event_JBUsuariosOptionMousePressed

    private void JBUsuariosRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBUsuariosRegistrarMousePressed
        String UsuPuesto = (String)JCUsuPuesto.getSelectedItem();
        if(!(JTUsuNombre.getText().equals("") || JTUsuPassword.getText().equals("") || JTUsuUsuario.getText().equals("")
               || UsuPuesto.equals(""))){
            Usuarios usu = new Usuarios(
                JTUsuUsuario.getText(),
                JTUsuPassword.getText(),
                JTUsuNombre.getText(),
                UsuPuesto);
            try{
                if(usu.saveData() > 0){
                    JCUsuPuesto.setSelectedItem("Selecciona una Opcion");
                    JTUsuNombre.setText("");
                    JTUsuPassword.setText("");
                    JTUsuUsuario.setText("");
                }else{
                    System.out.println("falla al registrar");
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_JBUsuariosRegistrarMousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Document documento = new Document();
        String ID = txt_buscar.getText().trim();
        String ruta = System.getProperty("user.home");
        try{
            PdfWriter.getInstance(documento, new FileOutputStream("C:/Users/Cesar/Desktop/Reporte_Obras.pdf"));
            documento.open();

            PdfPTable tabla =  new PdfPTable(6);
            tabla.addCell("Codigo");
            tabla.addCell("Nombre Obra");
            tabla.addCell("Genero");
            tabla.addCell("Duracion");
            tabla.addCell("NUM-asientos");
            tabla.addCell("Fecha7Hora");
        
            ObraTeatro teatro = new ObraTeatro( Integer.parseInt(ID) );
            teatro.SearchObras();
            tabla.addCell(String.valueOf(teatro.get_ID()));
            tabla.addCell(teatro.get_Nombre());
            tabla.addCell(teatro.get_Genero());
            tabla.addCell(teatro.get_Duracion());
            tabla.addCell(String.valueOf(teatro.get_Num_Lugares()));
            tabla.addCell(teatro.get_Fecha_Hora());
            documento.add(tabla);
        
            documento.close();
            JOptionPane.showInputDialog("Pdf Generado");
        }catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            ObraTeatro teatro = new ObraTeatro(
                txt_nombre.getText(),
                txt_genero.getText(),
                txt_Duracion.getText(),
                Integer.parseInt(txt_asientos.getText()),
                txt_fecha.getText()
            );
            
            if(teatro.saveData() > 0){
                txt_nombre.setText("");
                txt_genero.setText("");
                txt_Duracion.setText("");
                txt_asientos.setText("");
                txt_fecha.setText("");
                status.setText("Registro Exitoso");
            }else{
                System.out.println("falla al registrar");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            String ID = txt_buscar.getText().trim();

            ObraTeatro teatro = new ObraTeatro(
                Integer.parseInt(ID),
                txt_nombre.getText(),
                txt_genero.getText(),
                txt_Duracion.getText(),
                Integer.parseInt(txt_asientos.getText()),
                txt_fecha.getText()
            );
            
            if(teatro.updateData() > 0){
                status.setText("Modificacion Exitosa");
            }else{
                System.out.println("falla al registrar");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            ObraTeatro teatro = new ObraTeatro(Integer.parseInt(txt_buscar.getText()));
            if(teatro.deleteData() > 0){
                txt_nombre.setText("");
                txt_genero.setText("");
                txt_Duracion.setText("");
                txt_asientos.setText("");
                txt_fecha.setText("");
                txt_buscar.setText("");

                status.setText("Registro Eliminado");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            ObraTeatro teatro = new ObraTeatro(Integer.parseInt(txt_buscar.getText()));
            teatro.SearchObras();
            if(teatro.get_Nombre() != null){
                txt_nombre.setText(teatro.get_Nombre());
                txt_genero.setText(teatro.get_Genero());
                txt_Duracion.setText(teatro.get_Duracion());
                txt_asientos.setText(String.valueOf(teatro.get_Num_Lugares()));
                txt_fecha.setText(teatro.get_Fecha_Hora());
            }else{
                JOptionPane.showMessageDialog(null, "Obra no registrada");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void JBBoletosRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBBoletosRegistroMousePressed
        String Obra = (String)JCBoletosObra.getSelectedItem();
        String NAsientos = (String)JCBoletosNAsientos.getSelectedItem();
        String Vip = (String)JCBoletosVip.getSelectedItem();

        if(!(JCBoletosNombreCli.getText().equals("") || JCBoletosTelCli.getText().equals("") || JCBoletosEdadCli.getText().equals("")
               || Vip.equals("") || NAsientos.equals("") || Obra.equals(""))){
            VentaBoletos boleto = new VentaBoletos(
                Obra,
                NAsientos,
                Vip.equals("Si"),
                JCBoletosNombreCli.getText(),
                JCBoletosTelCli.getText(),
                Integer.parseInt(JCBoletosEdadCli.getText()));
            try{
                if(boleto.saveData() > 0){
                    JCBoletosObra.setSelectedItem("Selecciona una opcion");
                    JCBoletosNAsientos.setSelectedItem("Selecciona una Opcion");
                    JCBoletosNAsientos.setEnabled(false);
                    JCBoletosVip.setSelectedItem("Selecciona una opcion");
                    JCBoletosNombreCli.setText("");
                    JCBoletosTelCli.setText("");
                    JCBoletosEdadCli.setText("");
                }else{
                    System.out.println("falla al registrar");
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_JBBoletosRegistroMousePressed

    private void JCBoletosObraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCBoletosObraItemStateChanged
        String ObraSelect = (String)JCBoletosObra.getSelectedItem();
        try{
            ObraTeatro ListTeatro = new ObraTeatro(ObraSelect);
            VentaBoletos Boletos = new VentaBoletos();
            int countAux = 0;
            ListTeatro.SearchObras();
            String[] ModelTeatro = new String[ListTeatro.get_Num_Lugares()];
            ModelTeatro[0] = "Selecciona una opcion";
            for (int i = 1; i < ListTeatro.get_Num_Lugares(); i++){
                if(!Boletos.validAsiento("A"+i, ObraSelect))
                    ModelTeatro[countAux++] = "A"+i;
                
            }
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>( ModelTeatro );
            JCBoletosNAsientos.setEnabled(true);
            JCBoletosNAsientos.setModel( model );
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_JCBoletosObraItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        Document documento = new Document();
        String ID = txt_buscar.getText().trim();
        String ruta = System.getProperty("user.home");
        try{
            PdfWriter.getInstance(documento, new FileOutputStream("C:/Users/Cesar/Desktop/Boletos.pdf"));
            documento.open();
             
            PdfPTable tabla =  new PdfPTable(6);
            tabla.addCell("id_boleto");
            tabla.addCell("id_obra");
            tabla.addCell("posicion_asiento");
            tabla.addCell("vip");
            tabla.addCell("estatus_boleto");
            tabla.addCell("nombre_cliente");
            
            VentaBoletos boletos = new VentaBoletos();
            ArrayList<VentaBoletos> ListBoletos = boletos.ListBoletos();
            
            for( VentaBoletos Boletos : ListBoletos){
                tabla.addCell(Integer.toString(Boletos.getid_boleto()));
                tabla.addCell(Boletos.getid_obra());
                tabla.addCell(Boletos.getposicion_asiento());
                tabla.addCell(Boletos.getvip()? "VIP": "NORMAL");
                tabla.addCell(Boletos.getestatus_boleto()? "Activo": "No Activo");
                tabla.addCell(Boletos.getnombre_cliente());
            }

            documento.add(tabla);
            documento.close();
            JOptionPane.showMessageDialog(null, "Pdf Generado");
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        Document documento = new Document();
        String ID = txt_buscar.getText().trim();
        String ruta = System.getProperty("user.home");
        try{
            PdfWriter.getInstance(documento, new FileOutputStream("C:/Users/Cesar/Desktop/Usuarios.pdf"));
            documento.open();
             
            PdfPTable tabla =  new PdfPTable(4);
            tabla.addCell("usuario");
            tabla.addCell("nombre");
            tabla.addCell("puesto");
            tabla.addCell("estatus");
            
            Usuarios usua = new Usuarios();
            ArrayList<Usuarios> ListaUsuarios = usua.ListUsuarios();
            
            for( Usuarios usuario : ListaUsuarios){
                tabla.addCell(usuario.get_usuario());
                tabla.addCell(usuario.get_nombre());
                tabla.addCell(usuario.get_puesto());
                tabla.addCell(usuario.get_estatus()? "Activo": "Inactivo");
            }

            documento.add(tabla);
            documento.close();
            JOptionPane.showMessageDialog(null, "Pdf Generado");
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton8MousePressed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        Document documento = new Document();
        String ID = txt_buscar.getText().trim();
        String ruta = System.getProperty("user.home");
        try{
            PdfWriter.getInstance(documento, new FileOutputStream("C:/Users/Cesar/Desktop/Obras.pdf"));
            documento.open();
             
            PdfPTable tabla =  new PdfPTable(6);
            tabla.addCell("ID");
            tabla.addCell("Nombre");
            tabla.addCell("Genero");
            tabla.addCell("Duracion");
            tabla.addCell("Num_Lugares");
            tabla.addCell("Fecha_Hora");
            
            ObraTeatro obrat = new ObraTeatro();
            ArrayList<ObraTeatro> ListaObraTeatros = obrat.ListObraTeatro();
            
            for( ObraTeatro Obra : ListaObraTeatros){
                tabla.addCell(String.valueOf(Obra.get_ID()));
                tabla.addCell(Obra.get_Nombre());
                tabla.addCell(Obra.get_Genero());
                tabla.addCell(Obra.get_Duracion());
                tabla.addCell(String.valueOf(Obra.get_Num_Lugares()));
                tabla.addCell(Obra.get_Fecha_Hora());
            }

            documento.add(tabla);
            documento.close();
            JOptionPane.showMessageDialog(null, "Pdf Generado");
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7MousePressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        char c = evt.getKeyChar();
        try{
            if (c == KeyEvent.VK_ENTER && !jTextField1.getText().equals("")) {
                String usuario = jTextField1.getText();
                Usuarios usu = new Usuarios(usuario);
                if(usu.disabledUsuario() > 0){
                    if(usu.get_usuario().equals(usuarioSession)){
                        System.exit(0);
                    }else{
                        JOptionPane.showMessageDialog(null, "Usuario desactivado");
                        setMenuOptions("Usuarios");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boletos;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton JBBoletosRegistro;
    private javax.swing.JButton JBUsuariosOption;
    private javax.swing.JButton JBUsuariosRegistrar;
    private javax.swing.JTextField JCBoletosEdadCli;
    private javax.swing.JComboBox<String> JCBoletosNAsientos;
    private javax.swing.JTextField JCBoletosNombreCli;
    private javax.swing.JComboBox<String> JCBoletosObra;
    private javax.swing.JTextField JCBoletosTelCli;
    private javax.swing.JComboBox<String> JCBoletosVip;
    private javax.swing.JComboBox<String> JCUsuPuesto;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JLabel JLUsuariosTitulo;
    private javax.swing.JPanel JPBoletos;
    private javax.swing.JPanel JPObras;
    private javax.swing.JPanel JPReportes;
    private javax.swing.JPanel JPUsuarios;
    private javax.swing.JPanel JPUsuariosContent;
    private javax.swing.JPanel JPUsuariosHeader;
    private javax.swing.JTable JTListaUsuarios;
    private javax.swing.JTextField JTUsuNombre;
    private javax.swing.JTextField JTUsuPassword;
    private javax.swing.JTextField JTUsuUsuario;
    private javax.swing.JPanel Logo;
    private javax.swing.JButton Obras;
    private javax.swing.JButton Reportes;
    private javax.swing.JButton Usuarios;
    private javax.swing.JPanel UsuariosContentAgregar;
    private javax.swing.JPanel UsuariosContentLista;
    private javax.swing.JPanel background;
    private javax.swing.JPanel content;
    private javax.swing.JPanel contentOptions;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel status;
    private javax.swing.JTextField txt_Duracion;
    private javax.swing.JTextField txt_asientos;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_genero;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
    
    
    public void setMenuOptions(String menu){
        JPReportes.setVisible(menu.equals("Reportes"));
        JPBoletos.setVisible(menu.equals("Boletos"));
        JPUsuarios.setVisible(menu.equals("Usuarios"));
        JPObras.setVisible(menu.equals("Obras"));
        
        JLTitulo.setText(menu);
        
        if(menu.equals("Usuarios")){
            setMenuUsuariosOptions("Lista de usuarios");
        }else if(menu.equals("Boletos")){
            try{
                ObraTeatro ListTeatro = new ObraTeatro();
                int auxCount = 0;
                ArrayList<ObraTeatro> AuxListTeatro = ListTeatro.ListObraTeatro();
                String[] ModelTeatro = new String[AuxListTeatro.size() + 1];
                ModelTeatro[auxCount++] = "Selecciona una opcion";
                for ( ObraTeatro Teatro : AuxListTeatro){
                    ModelTeatro[auxCount++] = Teatro.get_Nombre();
                }
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>( ModelTeatro );
                JCBoletosObra.setModel( model );
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }
    
    public void setMenuUsuariosOptions(String menu){
        UsuariosContentAgregar.setVisible(menu.equals("Agregar usuario"));
        UsuariosContentLista.setVisible(menu.equals("Lista de usuarios"));
        JLUsuariosTitulo.setText(menu);

        if(menu.equals("Agregar usuario")){
            JBUsuariosOption.setLabel("Lista");
        }else if(menu.equals("Lista de usuarios")){
            Usuarios usu = new Usuarios();
            try{
                ArrayList<Usuarios> ListaUsuarios = usu.ListUsuarios();
                global.removeAllTable(JTListaUsuarios);
                for(Usuarios usuario: ListaUsuarios)
                    global.addElementTable(JTListaUsuarios, new Object[]{
                        usuario.get_usuario(),
                        usuario.get_nombre(),
                        usuario.get_puesto(),
                        usuario.get_estatus()? "Activo": "No activo"
                    });
            }catch(Exception e){
                System.out.println(e);
            }
            
            JBUsuariosOption.setLabel("Agregar");
        }
    }
}
